version: '3'
services:
    redis:
        image: redis:alpine
        expose:
            - 6379
    celery:
        image: haliphax/flaskbb:latest
        depends_on:
            - redis
        command: 'flaskbb --config=config/flaskbb.cfg celery worker'
        volumes:
            - ./config:/app/config
            - ./data:/app/data
    web:
        image: haliphax/flaskbb:latest
        depends_on:
            - celery
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./themes:/usr/local/lib/python2.7/site-packages/flaskbb/themes
        ports:
            - 80:5000
