version: '3'
services:
    redis:
        image: redis:alpine
        expose:
            - 6379
    web:
        image: haliphax/flaskbb:latest
        depends_on:
            - redis
        volumes:
            - ./config:/app/config
            - ./data:/app/data
            - ./themes:/app/flaskbb/flaskbb/themes
        ports:
            - 80:5000
